# Generated by Django 6.0.4 on 2026-04-18 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('wells', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_type', models.CharField(blank=True, default='CaCl2', max_length=60)),
                ('sg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('yield_value', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Completion fluid volume (bbls)', max_digits=8, null=True)),
                ('packaging_kg_per_sax', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Packaging (kg/sax)')),
                ('perforation_intervals', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoringInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('depth_from_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Depth from (m)')),
                ('depth_to_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Depth to (m)')),
                ('coring_mtrg_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Coring meterage (m)')),
                ('oh_section_inch', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='OH section (inch)')),
                ('completion_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coring_intervals', to='proposals.completionspec')),
            ],
            options={
                'ordering': ['completion_spec_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, max_length=60, unique=True)),
                ('version', models.CharField(default='2.4/2017', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('date_input', models.DateField(blank=True, help_text='Tanggal input proposal (DD-MMM-YYYY dari A.Proposal row 9)', null=True)),
                ('spud_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('mob_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('demob_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dollar_rate', models.DecimalField(blank=True, decimal_places=2, help_text='USD/IDR exchange rate at time of proposal', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted (awaiting supervisor)'), ('UNDER_REVIEW', 'Under review (management)'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION', 'Revision requested'), ('TEMPLATE', 'Template')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('total_dryhole_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_completion_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_rig_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals_created', to=settings.AUTH_USER_MODEL)),
                ('rig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='masterdata.rigspec')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='wells.well')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_name', models.CharField(help_text='e.g. LENGTH PER STAND, RATE FOR RIH/POOH BHA & TBG', max_length=120)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(help_text='e.g. MTR, MIN/STDS, MIN/JTS', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_rates', to='proposals.proposal')),
            ],
            options={
                'ordering': ['proposal_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FormationMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='e.g. Cisubuh, Parigi, CBA', max_length=120)),
                ('depth_md', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Depth MD (m)')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_markers', to='proposals.proposal')),
            ],
            options={
                'ordering': ['proposal_id', 'order'],
            },
        ),
        migrations.AddField(
            model_name='completionspec',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_spec', to='proposals.proposal'),
        ),
        migrations.CreateModel(
            name='CasingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('od_csg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('id_csg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('weight_lbs_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('depth_m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('top_of_liner_m', models.DecimalField(blank=True, decimal_places=2, help_text='Top of Liner (mMD). Isi hanya untuk liner, kosongkan untuk casing penuh.', max_digits=10, null=True, verbose_name='TOL (mMD)')),
                ('is_completion', models.BooleanField(default=False, help_text='Check if this row represents the completion phase (not dry hole).')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sg_from', models.DecimalField(blank=True, decimal_places=3, help_text='Mud specific gravity lower bound', max_digits=6, null=True, verbose_name='SG From')),
                ('sg_to', models.DecimalField(blank=True, decimal_places=3, help_text='Mud specific gravity upper bound', max_digits=6, null=True, verbose_name='SG To')),
                ('casing_type', models.CharField(blank=True, help_text='Casing grade, e.g. K-55, N-80', max_length=30)),
                ('pounder', models.DecimalField(blank=True, decimal_places=2, help_text='Casing weight (lbs/ft) — pounder column', max_digits=8, null=True)),
                ('thread', models.CharField(blank=True, help_text='Thread type, e.g. BTC, LTC, STC', max_length=30)),
                ('range_spec', models.CharField(blank=True, help_text='Casing range, e.g. R-1, R-2, R-3', max_length=20)),
                ('casing_title', models.CharField(blank=True, help_text="Auto-generated casing summary, e.g. 13 3/8'' Csg, K-55, 54.5 ppf, BTC, R-3 at 734 mMD", max_length=255)),
                ('section_type', models.CharField(blank=True, help_text='Drilling section type from Tab 2.0, e.g. PRESPUD PREPARATION W/ ENDURANCE TEST', max_length=200)),
                ('drilling_days', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('non_drilling_days', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('completion_days', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('total_days', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('drilling_rate_m_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hole_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.holesection')),
                ('mud_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masterdata.mudtype')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casing_sections', to='proposals.proposal')),
            ],
            options={
                'ordering': ['proposal_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit to supervisor'), ('FORWARD', 'Forward to management'), ('REQUEST_REVISION', 'Request revision'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='proposals.proposal')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProposalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('hours_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use the default hours from the master activity.', max_digits=8, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.drillingactivity')),
                ('casing_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='proposals.casingsection')),
            ],
            options={
                'ordering': ['casing_section_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TubeLengthRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='R-1, R-2, R-3, SP', max_length=10)),
                ('avg_length_m', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Avg length (m)')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tube_length_ranges', to='proposals.proposal')),
            ],
            options={
                'ordering': ['proposal_id', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TubingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('od_inch', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='OD (inch)')),
                ('id_inch', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='ID (inch)')),
                ('weight_lbs_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight (lbs/ft)')),
                ('avg_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Avg length (m)')),
                ('depth_md', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Depth MD (m)')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tubing_items', to='proposals.proposal')),
            ],
            options={
                'ordering': ['proposal_id', 'order'],
            },
        ),
    ]
