# Generated by Django 6.0.4 on 2026-04-11 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('wells', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, max_length=60, unique=True)),
                ('version', models.CharField(default='2.4/2017', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('spud_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('mob_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('demob_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dollar_rate', models.DecimalField(blank=True, decimal_places=2, help_text='USD/IDR exchange rate at time of proposal', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted (awaiting supervisor)'), ('UNDER_REVIEW', 'Under review (management)'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION', 'Revision requested')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('total_dryhole_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_completion_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_rig_days', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals_created', to=settings.AUTH_USER_MODEL)),
                ('rig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='masterdata.rigspec')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='wells.well')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompletionSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt_type', models.CharField(blank=True, default='CaCl2', max_length=60)),
                ('sg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('yield_value', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('coring_depth_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coring_depth_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('perforation_intervals', models.TextField(blank=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_spec', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='CasingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('od_csg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('id_csg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('weight_lbs_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('depth_m', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tol_hours', models.DecimalField(decimal_places=2, default=0, help_text='Time on Location override (hours). Leave 0 to use activity sum.', max_digits=8)),
                ('is_completion', models.BooleanField(default=False, help_text='Check if this row represents the completion phase (not dry hole).')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('drilling_days', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('non_drilling_days', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('total_days', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('drilling_rate_m_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hole_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.holesection')),
                ('mud_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masterdata.mudtype')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casing_sections', to='proposals.proposal')),
            ],
            options={
                'ordering': ['proposal_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit to supervisor'), ('FORWARD', 'Forward to management'), ('REQUEST_REVISION', 'Request revision'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='proposals.proposal')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProposalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('hours_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use the default hours from the master activity.', max_digits=8, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.drillingactivity')),
                ('casing_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='proposals.casingsection')),
            ],
            options={
                'ordering': ['casing_section_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TubingSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_inch', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='OD (inch)')),
                ('id_inch', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='ID (inch)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('avg_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('formation_marker', models.CharField(blank=True, max_length=120)),
                ('depth_md', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tubing_spec', to='proposals.proposal')),
            ],
        ),
    ]
