# Generated by Django 6.0.4 on 2026-04-17 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tubingspec',
            options={'ordering': ['proposal_id', 'order']},
        ),
        migrations.RemoveField(
            model_name='tubingspec',
            name='formation_marker',
        ),
        migrations.AddField(
            model_name='casingsection',
            name='casing_title',
            field=models.CharField(blank=True, help_text="Auto-generated casing summary, e.g. 13 3/8'' Csg, K-55, 54.5 ppf, BTC, R-3 at 734 mMD", max_length=255),
        ),
        migrations.AddField(
            model_name='casingsection',
            name='casing_type',
            field=models.CharField(blank=True, help_text='Casing grade, e.g. K-55, N-80', max_length=30),
        ),
        migrations.AddField(
            model_name='casingsection',
            name='completion_days',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='casingsection',
            name='pounder',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Casing weight (lbs/ft) — pounder column', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='casingsection',
            name='range_spec',
            field=models.CharField(blank=True, help_text='Casing range, e.g. R-1, R-2, R-3', max_length=20),
        ),
        migrations.AddField(
            model_name='casingsection',
            name='section_type',
            field=models.CharField(blank=True, help_text='Drilling section type from Tab 2.0, e.g. PRESPUD PREPARATION W/ ENDURANCE TEST', max_length=200),
        ),
        migrations.AddField(
            model_name='casingsection',
            name='sg_from',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Mud specific gravity lower bound', max_digits=6, null=True, verbose_name='SG From'),
        ),
        migrations.AddField(
            model_name='casingsection',
            name='sg_to',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Mud specific gravity upper bound', max_digits=6, null=True, verbose_name='SG To'),
        ),
        migrations.AddField(
            model_name='casingsection',
            name='thread',
            field=models.CharField(blank=True, help_text='Thread type, e.g. BTC, LTC, STC', max_length=30),
        ),
        migrations.AddField(
            model_name='completionspec',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Completion fluid volume (bbls)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_input',
            field=models.DateField(blank=True, help_text='Tanggal input proposal (DD-MMM-YYYY dari A.Proposal row 9)', null=True),
        ),
        migrations.AddField(
            model_name='tubingspec',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted (awaiting supervisor)'), ('UNDER_REVIEW', 'Under review (management)'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION', 'Revision requested'), ('TEMPLATE', 'Template')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='tubingspec',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tubing_specs', to='proposals.proposal'),
        ),
        migrations.CreateModel(
            name='OperationalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_name', models.CharField(help_text='e.g. LENGTH PER STAND, RATE FOR RIH/POOH BHA & TBG', max_length=120)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(help_text='e.g. MTR, MIN/STDS, MIN/JTS', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_rates', to='proposals.proposal')),
            ],
            options={
                'ordering': ['proposal_id', 'order'],
            },
        ),
    ]
