# Generated by Django 5.1.15 on 2026-04-14 06:55
#
# Note: hand-edited from auto-generated Remove+Add to a RenameField + AlterField
# to preserve existing data. The semantics of the field also change here:
# old: tol_hours (DecimalField default=0, "Time on Location override hours")
# new: top_of_liner_m (DecimalField null/blank, "Top of Liner mMD")
#
# Existing values in tol_hours are CARRIED OVER as-is into top_of_liner_m. That
# is intentional — see plan: any non-zero existing value was almost certainly
# wrong (the field was unused in practice, db.sqlite3.bak available for rollback).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casingsection',
            old_name='tol_hours',
            new_name='top_of_liner_m',
        ),
        migrations.AlterField(
            model_name='casingsection',
            name='top_of_liner_m',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Top of Liner (mMD). Hanya diisi untuk casing liner; kosong untuk casing penuh.',
                max_digits=8,
                null=True,
            ),
        ),
    ]
