# Generated by Django 5.1.15 on 2026-04-14 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
        ('proposals', '0002_rename_tol_hours_to_top_of_liner_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='total_pre_spud_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='proposal',
            name='total_rig_release_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProposalPhaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PRE_SPUD', 'Pre Spud'), ('RIG_RELEASE', 'Rig Release')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hours_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use the default hours from the master activity.', max_digits=8, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masterdata.drillingactivity')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_activities', to='proposals.proposal')),
            ],
            options={
                'ordering': ['proposal_id', 'phase', 'order'],
                'indexes': [models.Index(fields=['proposal', 'phase'], name='proposals_p_proposa_d05ad2_idx')],
            },
        ),
    ]
