# Generated by Django 5.1.15 on 2026-04-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_proposal_phase_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='closed_out_date',
            field=models.DateTimeField(blank=True, help_text='Tanggal close-out proposal (Excel A.Proposal R13).', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='interval_total_perfo_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total panjang interval perforasi (Excel A.Proposal R76).', max_digits=8, null=True, verbose_name='Interval total perforasi (m)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='jarak_moving_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Jarak rig moving dari lokasi sebelumnya (km).', max_digits=8, null=True, verbose_name='Jarak moving (km)'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='no_afe',
            field=models.CharField(blank=True, help_text='No. AFE referensi (Excel A.Proposal R5).', max_length=60, verbose_name='No. AFE'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='placed_into_service',
            field=models.DateTimeField(blank=True, help_text='Tanggal sumur masuk service (Excel A.Proposal R12).', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='well_status',
            field=models.CharField(blank=True, help_text='Status well saat proposal dibuat (Excel A.Proposal R8).', max_length=60),
        ),
    ]
