# Generated by Django 5.1.15 on 2026-04-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_add_excel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='casingsection',
            name='sg_from',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mud specific gravity minimum (per-section).', max_digits=5, null=True, verbose_name='SG from'),
        ),
        migrations.AddField(
            model_name='casingsection',
            name='sg_to',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mud specific gravity maximum (per-section).', max_digits=5, null=True, verbose_name='SG to'),
        ),
    ]
