# Generated by Django 5.1.15 on 2026-04-16 01:45
# Hand-edited to add data migration for TubingSpec → TubingItem
# and CompletionSpec coring_depth_from/to → CoringInterval.

import django.db.models.deletion
from django.db import migrations, models


def migrate_tubing_data(apps, schema_editor):
    """Copy each TubingSpec row into a TubingItem row."""
    TubingSpec = apps.get_model("proposals", "TubingSpec")
    TubingItem = apps.get_model("proposals", "TubingItem")
    for ts in TubingSpec.objects.all():
        TubingItem.objects.create(
            proposal_id=ts.proposal_id,
            order=0,
            od_inch=ts.od_inch,
            id_inch=ts.id_inch,
            weight_lbs_ft=ts.weight,
            avg_length_m=ts.avg_length,
            depth_md=ts.depth_md,
        )


def migrate_coring_data(apps, schema_editor):
    """If CompletionSpec has coring_depth_from/to filled, create one CoringInterval."""
    CompletionSpec = apps.get_model("proposals", "CompletionSpec")
    CoringInterval = apps.get_model("proposals", "CoringInterval")
    for cs in CompletionSpec.objects.all():
        if cs.coring_depth_from is not None or cs.coring_depth_to is not None:
            CoringInterval.objects.create(
                completion_spec_id=cs.id,
                order=0,
                depth_from_m=cs.coring_depth_from,
                depth_to_m=cs.coring_depth_to,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_casing_sg_range'),
    ]

    operations = [
        # 1. Add new field to CompletionSpec
        migrations.AddField(
            model_name='completionspec',
            name='packaging_kg_per_sax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Packaging (kg/sax)'),
        ),
        # 2. Create new models first (before data migration)
        migrations.CreateModel(
            name='CoringInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('depth_from_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Depth from (m)')),
                ('depth_to_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Depth to (m)')),
                ('coring_mtrg_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Coring meterage (m)')),
                ('oh_section_inch', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='OH section (inch)')),
                ('completion_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coring_intervals', to='proposals.completionspec')),
            ],
            options={
                'ordering': ['completion_spec_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FormationMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='e.g. Cisubuh, Parigi, CBA', max_length=120)),
                ('depth_md', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Depth MD (m)')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_markers', to='proposals.proposal')),
            ],
            options={
                'ordering': ['proposal_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TubeLengthRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='R-1, R-2, R-3, SP', max_length=10)),
                ('avg_length_m', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Avg length (m)')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tube_length_ranges', to='proposals.proposal')),
            ],
            options={
                'ordering': ['proposal_id', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TubingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('od_inch', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='OD (inch)')),
                ('id_inch', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='ID (inch)')),
                ('weight_lbs_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight (lbs/ft)')),
                ('avg_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Avg length (m)')),
                ('depth_md', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Depth MD (m)')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tubing_items', to='proposals.proposal')),
            ],
            options={
                'ordering': ['proposal_id', 'order'],
            },
        ),
        # 3. Data migrations — copy old data to new models
        migrations.RunPython(migrate_tubing_data, migrations.RunPython.noop),
        migrations.RunPython(migrate_coring_data, migrations.RunPython.noop),
        # 4. Now safe to remove old fields/models
        migrations.RemoveField(
            model_name='completionspec',
            name='coring_depth_from',
        ),
        migrations.RemoveField(
            model_name='completionspec',
            name='coring_depth_to',
        ),
        migrations.DeleteModel(
            name='TubingSpec',
        ),
    ]
