# Generated by Django 6.0.4 on 2026-04-11 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategoryL1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Activity Category Level 1',
                'verbose_name_plural': 'Activity Categories Level 1',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HoleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_inch', models.DecimalField(decimal_places=3, help_text='Hole / open hole size in inches (e.g. 26, 17.5, 12.25)', max_digits=6, unique=True)),
                ('label', models.CharField(help_text='Display label, e.g. "26\\""', max_length=30)),
                ('default_od', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('default_id', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('default_weight_lbs_ft', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-size_inch'],
            },
        ),
        migrations.CreateModel(
            name='MudType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RigSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100, unique=True)),
                ('horsepower', models.PositiveIntegerField(blank=True, null=True)),
                ('floor_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rig specification',
                'verbose_name_plural': 'Rig specifications',
                'ordering': ['platform_name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityCategoryL2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='masterdata.activitycategoryl1')),
            ],
            options={
                'verbose_name': 'Activity Category Level 2',
                'verbose_name_plural': 'Activity Categories Level 2',
                'ordering': ['parent__order', 'order', 'name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RopRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_depth_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('end_depth_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('days', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rop_m_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hole_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rop_rates', to='masterdata.holesection')),
            ],
            options={
                'ordering': ['hole_section__size_inch', 'start_depth_m'],
            },
        ),
        migrations.CreateModel(
            name='DrillingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text="Excel 'Code' column (e.g. 1b, 2b)", max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('default_hours', models.DecimalField(decimal_places=2, default=0, help_text='Baseline hours from Tab 1.0 STD column', max_digits=8)),
                ('phase_type', models.CharField(choices=[('DRILLING', 'Drilling'), ('NON_DRILLING', 'Non-drilling'), ('COMPLETION', 'Completion')], default='DRILLING', max_length=20)),
                ('category_l2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='masterdata.activitycategoryl2')),
                ('applies_to_hole_sections', models.ManyToManyField(blank=True, help_text='If empty, activity applies to all hole sections', related_name='activities', to='masterdata.holesection')),
            ],
            options={
                'ordering': ['category_l2__parent__order', 'category_l2__order', 'code', 'description'],
                'indexes': [models.Index(fields=['phase_type'], name='masterdata__phase_t_5f6b66_idx')],
            },
        ),
    ]
