# Generated by Django 6.0.4 on 2026-04-18 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cluster', models.CharField(blank=True, help_text='e.g. CLUSTER BDA-G3', max_length=120)),
                ('location', models.CharField(blank=True, help_text='e.g. BDA-D1', max_length=120)),
                ('field', models.CharField(blank=True, help_text='e.g. BANGADUA', max_length=120)),
                ('basin', models.CharField(blank=True, help_text='e.g. JAWA BARAT', max_length=120)),
                ('operator', models.CharField(default='PT. PERTAMINA EP', max_length=120)),
                ('contract_area', models.CharField(default='INDONESIA / ASSET 3', max_length=120)),
                ('elevation_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('target_formation', models.CharField(blank=True, max_length=200)),
                ('surface_lat', models.CharField(blank=True, max_length=50)),
                ('surface_lon', models.CharField(blank=True, max_length=50)),
                ('target_lat', models.CharField(blank=True, max_length=50)),
                ('target_lon', models.CharField(blank=True, max_length=50)),
                ('project_type', models.CharField(choices=[('DRILLING_ONLY', 'Drilling only'), ('DRILLING_COMPLETION', 'Drilling and Completion'), ('WORKOVER', 'Workover')], default='DRILLING_COMPLETION', max_length=30)),
                ('well_type', models.CharField(choices=[('VERTICAL', 'Vertical'), ('DIRECTIONAL', 'Directional'), ('HORIZONTAL', 'Horizontal')], default='DIRECTIONAL', max_length=20)),
                ('well_category', models.CharField(choices=[('EXPLORATION', 'Exploration'), ('DEVELOPMENT', 'Development'), ('APPRAISAL', 'Appraisal')], default='DEVELOPMENT', max_length=20)),
                ('inclination_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('azimuth_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('kop_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('overlap_liner_7in_m', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: depth casing sebelumnya − TOL liner 7"', max_digits=8, null=True, verbose_name='Overlap Liner 7"')),
                ('overlap_liner_4in_m', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: depth casing sebelumnya − TOL liner 4-1/2"', max_digits=8, null=True, verbose_name='Overlap Liner 4.5"')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'location')},
            },
        ),
        migrations.CreateModel(
            name='FormationMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Cisubuh, Parigi, CBA', max_length=120)),
                ('depth_m', models.DecimalField(decimal_places=2, help_text='Depth in mMD', max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_markers', to='wells.well')),
            ],
            options={
                'ordering': ['well_id', 'order'],
                'unique_together': {('well', 'name')},
            },
        ),
    ]
