# Generated by Django 6.0.4 on 2026-04-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cluster', models.CharField(blank=True, help_text='e.g. CLUSTER BDA-G3', max_length=120)),
                ('location', models.CharField(blank=True, help_text='e.g. BDA-D1', max_length=120)),
                ('field', models.CharField(blank=True, help_text='e.g. BANGADUA', max_length=120)),
                ('basin', models.CharField(blank=True, help_text='e.g. JAWA BARAT', max_length=120)),
                ('operator', models.CharField(default='PT. PERTAMINA EP', max_length=120)),
                ('contract_area', models.CharField(default='INDONESIA / ASSET 3', max_length=120)),
                ('elevation_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('target_formation', models.CharField(blank=True, max_length=200)),
                ('surface_lat', models.CharField(blank=True, max_length=50)),
                ('surface_lon', models.CharField(blank=True, max_length=50)),
                ('target_lat', models.CharField(blank=True, max_length=50)),
                ('target_lon', models.CharField(blank=True, max_length=50)),
                ('project_type', models.CharField(choices=[('DRILLING_ONLY', 'Drilling only'), ('DRILLING_COMPLETION', 'Drilling and Completion'), ('WORKOVER', 'Workover')], default='DRILLING_COMPLETION', max_length=30)),
                ('well_type', models.CharField(choices=[('VERTICAL', 'Vertical'), ('DIRECTIONAL', 'Directional'), ('HORIZONTAL', 'Horizontal')], default='DIRECTIONAL', max_length=20)),
                ('well_category', models.CharField(choices=[('EXPLORATION', 'Exploration'), ('DEVELOPMENT', 'Development'), ('APPRAISAL', 'Appraisal')], default='DEVELOPMENT', max_length=20)),
                ('inclination_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('azimuth_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('kop_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'location')},
            },
        ),
    ]
