# Generated by Django 5.1.15 on 2026-04-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='overlap_liner_4_5_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Overlap 4-1/2" liner (m)'),
        ),
        migrations.AddField(
            model_name='well',
            name='overlap_liner_7_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Overlap 7" liner (m)'),
        ),
    ]
