# Generated by Django 6.0.4 on 2026-04-17 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='overlap_liner_4in_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overlap liner 4.5 inch (mMD) — from A.Proposal row 25', max_digits=8, null=True, verbose_name='Overlap Liner 4.5"'),
        ),
        migrations.AddField(
            model_name='well',
            name='overlap_liner_7in_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overlap liner 7 inch (mMD) — from A.Proposal row 24', max_digits=8, null=True, verbose_name='Overlap Liner 7"'),
        ),
        migrations.CreateModel(
            name='FormationMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Cisubuh, Parigi, CBA', max_length=120)),
                ('depth_m', models.DecimalField(decimal_places=2, help_text='Depth in mMD', max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_markers', to='wells.well')),
            ],
            options={
                'ordering': ['well_id', 'order'],
                'unique_together': {('well', 'name')},
            },
        ),
    ]
