# Generated by Django 6.0.4 on 2026-04-11 15:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AFETemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('TANGIBLE', 'Tangible'), ('INTANGIBLE', 'Intangible')], max_length=20)),
                ('section', models.CharField(choices=[('TANGIBLE', 'Tangible Cost'), ('PREPARATION', 'Preparation & Termination'), ('DRILLING', 'Drilling / Workover'), ('FORMATION', 'Formation Evaluation'), ('COMPLETION', 'Completion'), ('GENERAL', 'General / Overhead')], max_length=20)),
                ('calc_method', models.CharField(choices=[('RIG_DAYS_RATE', 'Rig days × daily rate'), ('DHB_CB_SPLIT', 'DHB days × rate + CB days × rate'), ('PER_METER_DEPTH', 'Max depth × rate per meter'), ('PER_CASING_WEIGHT', 'Σ casing weight × rate/lb'), ('LUMP_SUM', 'Flat lump sum'), ('MANUAL', 'Manual input')], default='MANUAL', max_length=30)),
                ('is_subtotal_row', models.BooleanField(default=False, help_text="Subtotal / header rows aren't filled by engineer.")),
                ('order', models.PositiveIntegerField(default=0)),
                ('default_rate_code', models.CharField(blank=True, help_text='Optional hint for picking default RateCardItem code.', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['order', 'line_code'],
            },
        ),
        migrations.CreateModel(
            name='AFE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('doc_number', models.CharField(blank=True, max_length=80, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION', 'Needs Revision')], default='DRAFT', max_length=20)),
                ('contingency_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('exchange_rate_override', models.DecimalField(blank=True, decimal_places=4, help_text='USD→IDR rate. Kalau kosong pakai proposal.dollar_rate.', max_digits=14, null=True)),
                ('total_tangible_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total_intangible_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('contingency_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('grand_total_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('cost_per_meter_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cost_per_day_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afes_created', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afes', to='proposals.proposal')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('proposal', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AFEApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('afe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='afe.afe')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RateCardImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('items_created', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RateCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('unit_of_measure', models.CharField(blank=True, max_length=30)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('phase_flag', models.CharField(choices=[('DHB', 'Dry Hole Based'), ('CB', 'Completion Based'), ('BOTH', 'Both')], default='BOTH', max_length=5)),
                ('material_type', models.CharField(blank=True, max_length=30)),
                ('source_sheet', models.CharField(blank=True, default='D.MATE', max_length=30)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('afe_line', models.ForeignKey(blank=True, help_text='Which AFE line this rate feeds by default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_items', to='afe.afetemplate')),
            ],
            options={
                'ordering': ['afe_line__order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AFELine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot dari rate card saat AFE dibuat.', max_digits=14, null=True)),
                ('calculated_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('override_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('afe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='afe.afe')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='afe.afetemplate')),
                ('rate_card_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='afe.ratecarditem')),
            ],
            options={
                'ordering': ['template__order', 'template__line_code'],
            },
        ),
        migrations.AddIndex(
            model_name='ratecarditem',
            index=models.Index(fields=['afe_line', 'phase_flag'], name='afe_ratecar_afe_lin_871a8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='afeline',
            unique_together={('afe', 'template')},
        ),
    ]
