# Generated by Django 6.0.4 on 2026-04-17 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFELineComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit_of_measure', models.CharField(blank=True, max_length=30)),
                ('unit_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('material_type', models.CharField(blank=True, help_text='MATERIAL or NON MATERIAL', max_length=30)),
                ('material_category', models.CharField(blank=True, help_text='SKK MIGAS category, e.g. Drive pipe, Conductor casing', max_length=60)),
                ('stock_status', models.CharField(blank=True, help_text='STOCK or NEW', max_length=20)),
                ('phase_flag', models.CharField(choices=[('DHB', 'Dry Hole Based'), ('CB', 'Completion Based'), ('BOTH', 'Both')], default='BOTH', help_text='DHB, CB, or BOTH', max_length=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('afe_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='afe.afeline')),
            ],
            options={
                'ordering': ['afe_line_id', 'order'],
            },
        ),
    ]
